"""
The intelligent stakeholder decision-making LLM agent — the "brain" of Stage 3.

Unlike a simple classifier, this agent:
  - Receives the COMPLETE picture from Stage 1 + Stage 2 in a single brief
  - Reasons holistically the way a Senior Compliance Officer would
  - Makes decisions at multiple levels simultaneously:
      * Individual Tier 3 case actions  (what to do right now per record)
      * Department-level directives     (patterns affecting entire departments)
      * Payer-level directives          (insurance company-specific findings)
      * Pipeline feedback               (should the ML model be retrained?)
      * Executive summary               (for senior management reporting)

One LLM call.  Complete situational intelligence in, complete decision brief out.

Decision output shape:
    {
      situation_assessment : str   — concise read of today's overall risk
      risk_level           : str   — CRITICAL | HIGH | MEDIUM | LOW
      immediate_actions    : list  — prioritized per-case actions (right now)
      department_directives: list  — department-level audit/review orders
      payer_directives     : list  — payer/insurance escalation decisions
      pipeline_feedback    : dict  — model health, retraining signal, thresholds
      executive_summary    : str   — one-paragraph brief for management
    }
"""
from __future__ import annotations

from typing import Any

from loguru import logger

from .llm_client import OllamaClient

_VALID_RISK_LEVELS = {"CRITICAL", "HIGH", "MEDIUM", "LOW"}

# ── System prompt ─────────────────────────────────────────────────────────────
# Frames the LLM as a senior compliance officer with full situational authority.

_SYSTEM_PROMPT = """\
You are a Senior Healthcare Billing Compliance Officer with authority over fraud \
investigation, revenue recovery, and regulatory compliance.

Every day you receive an automated anomaly detection briefing generated by a \
three-track pipeline:
  Track A — Cluster-level machine learning (Isolation Forest per patient cluster)
  Track B — Global machine learning (Global Isolation Forest across all patients)
  Track C — Deterministic business rules (charge z-score, claim/payment mismatches)

Records are tiered by how many tracks fired:
  Tier 3 — All 3 tracks fired → investigate immediately
  Tier 2 — Any 2 tracks fired → scheduled compliance review
  Tier 1 — Only 1 track fired → monitor
  Tier 0 — No tracks fired    → normal

You have read today's situation brief and must now produce a COMPLETE DECISION \
BRIEF covering every level of the organization.

Return a single valid JSON object with EXACTLY these fields:

{
  "situation_assessment": "<2-3 sentence read of today's overall risk and what \
it means for the organization>",

  "risk_level": "<CRITICAL | HIGH | MEDIUM | LOW>",

  "immediate_actions": [
    {
      "priority": <integer, 1 = highest>,
      "case_ref": "<patient_id or 'batch' for multi-case actions>",
      "action": "<specific action to take today>",
      "owner": "<who executes this: Fraud Investigation Unit | Billing Dept | \
Department Head | Payer Relations | Compliance Manager>",
      "reason": "<why this action is needed — reference the specific signals>"
    }
  ],

  "department_directives": [
    {
      "department": "<department name>",
      "finding": "<what the data shows about this department>",
      "directive": "<specific audit or corrective instruction>",
      "timeline": "<today | this week | this month>"
    }
  ],

  "payer_directives": [
    {
      "payer": "<payer or insurance company name>",
      "finding": "<payment or claim pattern observed>",
      "directive": "<action for payer relations or billing team>"
    }
  ],

  "pipeline_feedback": {
    "model_health": "<HEALTHY | NEEDS_REVIEW | RETRAIN_RECOMMENDED>",
    "observations": ["<observation about model behaviour>"],
    "threshold_recommendations": ["<any threshold adjustment suggestions>"],
    "data_quality_flags": ["<any data quality issues noticed>"]
  },

  "executive_summary": "<one concise paragraph for senior management — total \
records, critical count, primary risk, estimated revenue impact if known, and \
the top action being taken>"
}

Rules:
  - immediate_actions must cover every Tier 3 case individually.
  - department_directives and payer_directives only when patterns are present.
  - pipeline_feedback is always required (even if model_health is HEALTHY).
  - Base every decision strictly on the evidence in the brief — do not invent data.
  - Output JSON only.  No preamble, no commentary outside the JSON.\
"""

# ── User prompt ───────────────────────────────────────────────────────────────
# Appends the situation brief and gives the agent its decision mandate.

_USER_PROMPT_TEMPLATE = """\
{situation_brief}

=== YOUR MANDATE ===
You have read the situation brief above.  Now produce your complete decision \
brief as a Senior Compliance Officer responsible for this daily batch.
Treat each Tier 3 case as a real patient account requiring a real decision.
Your decisions will be executed by the billing and compliance teams today.

Return JSON only.\
"""


class DecisionAgent:
    """
    Holistic stakeholder LLM that makes multi-level decisions from the
    full Stage 1 + Stage 2 situation brief.
    """

    def __init__(self, llm: OllamaClient | None = None) -> None:
        self._llm = llm or OllamaClient()

    def decide(self, situation_brief: str) -> dict[str, Any]:
        """
        Issue a single LLM call and return the complete decision brief.

        Args:
            situation_brief: The structured plain-text brief from ContextBuilder.

        Returns:
            Validated decision dict, or a safe fallback if the LLM fails.
        """
        user_prompt = _USER_PROMPT_TEMPLATE.format(situation_brief=situation_brief)

        raw = self._llm.chat_json(
            system_prompt = _SYSTEM_PROMPT,
            user_prompt   = user_prompt,
            fallback      = _safe_fallback(),
        )

        result = _validate(raw)

        logger.info(
            "DecisionAgent.decide | risk_level={} | immediate_actions={} | "
            "department_directives={} | payer_directives={}",
            result.get("risk_level"),
            len(result.get("immediate_actions", [])),
            len(result.get("department_directives", [])),
            len(result.get("payer_directives", [])),
        )
        return result


# ── module helpers ────────────────────────────────────────────────────────────

def _validate(raw: dict[str, Any]) -> dict[str, Any]:
    """Enforce required structure; fill defaults for any missing fields."""

    # Risk level
    risk = str(raw.get("risk_level", "HIGH")).upper()
    if risk not in _VALID_RISK_LEVELS:
        risk = "HIGH"
    raw["risk_level"] = risk

    # Ensure list fields are lists
    for field in ("immediate_actions", "department_directives", "payer_directives"):
        if not isinstance(raw.get(field), list):
            raw[field] = []

    # Ensure immediate_actions items have required keys
    clean_actions = []
    for i, action in enumerate(raw.get("immediate_actions", []), 1):
        if not isinstance(action, dict):
            continue
        clean_actions.append({
            "priority":  action.get("priority", i),
            "case_ref":  action.get("case_ref", "N/A"),
            "action":    action.get("action", "Review this record manually."),
            "owner":     action.get("owner", "Compliance Manager"),
            "reason":    action.get("reason", ""),
        })
    raw["immediate_actions"] = sorted(clean_actions, key=lambda x: int(x.get("priority", 99)))

    # Pipeline feedback
    pf = raw.get("pipeline_feedback")
    if not isinstance(pf, dict):
        raw["pipeline_feedback"] = {
            "model_health": "HEALTHY",
            "observations": [],
            "threshold_recommendations": [],
            "data_quality_flags": [],
        }
    else:
        for list_field in ("observations", "threshold_recommendations", "data_quality_flags"):
            if not isinstance(pf.get(list_field), list):
                pf[list_field] = []

    # Fallbacks for text fields
    if not raw.get("situation_assessment"):
        raw["situation_assessment"] = "Situation assessment unavailable — manual review required."
    if not raw.get("executive_summary"):
        raw["executive_summary"] = "Executive summary unavailable — manual review required."

    return raw


def _safe_fallback() -> dict[str, Any]:
    """Returned when the LLM call fails entirely."""
    return {
        "situation_assessment": (
            "LLM decision engine unavailable.  All flagged records require manual review. "
            "Check that Ollama is running: `ollama serve` and model is pulled: `ollama pull llama3.2`."
        ),
        "risk_level": "HIGH",
        "immediate_actions": [
            {
                "priority": 1,
                "case_ref": "all_tier3",
                "action":   "Manually review all Tier 3 cases — LLM engine offline.",
                "owner":    "Compliance Manager",
                "reason":   "Automated decision agent could not connect to local Ollama server.",
            }
        ],
        "department_directives": [],
        "payer_directives":      [],
        "pipeline_feedback": {
            "model_health":              "NEEDS_REVIEW",
            "observations":              ["Decision LLM (Ollama) is not reachable."],
            "threshold_recommendations": [],
            "data_quality_flags":        [],
        },
        "executive_summary": (
            "Decision automation is offline.  Compliance team must perform manual triage of "
            "all flagged records.  Stage 1 and Stage 2 detection outputs remain valid."
        ),
    }
